baseURL = 'https://www.getinyourtree.com/'
languageCode = 'en-us'
title = 'ACME Get In Your Tree'

[params]
  description = 'Welcome to home of get ACMEs Get In Your Tree initiative.'
  author = 'ACME Inc'
